# Generated by Django 3.1 on 2020-08-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderable5', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='articleaggregation',
            old_name='agg_article_id',
            new_name='agg_article',
        ),
        migrations.RenameField(
            model_name='articleaggregation',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='orderablestorearticles',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='orderablestorearticles',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
    ]
