# Generated by Django 3.1 on 2020-08-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderable5', '0002_auto_20200812_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='articleaggregation',
            old_name='agg_article',
            new_name='agg_article_id',
        ),
        migrations.RenameField(
            model_name='articleaggregation',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='orderablestorearticles',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='orderablestorearticles',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order',
            new_name='order_id',
        ),
    ]
